# What do we mean "Generative" music?

## Generative: {.unnumbered}

"Generative" music is where, following some trigger event such as
pressing "play" or playing a note, or initiating some voltage (in
modular synthesis rack), the music follows some rules, algorithms or
uses probability to generate or evolve the musical ideas (notes,
rhythms, timbres) for an arbitrary amount of time. In some cases the
generative algorithms work ***with*** the performer, reacting to their
input. In other cases the performer may intervene with the algorithms to
tweak, adjust or change direction.

::: callout-tip
## Key idea

Generative music means (to me) that the music should be able to go on
indefinitely, evolving over time rather than being simply repetitive.

In the context of generative ***ambient*** music, it should have enough
going on to make it interesting, but without anything particularly
"sticking out" to catch the listener's ear.
:::

Some generative algorithms take parts that the performer plays and
augments this with additional harmony, chords or (counter) melodies. An
example of this is [Olafur Arnalds' and Halldór Eldjárn's Stratus
algorithm for performer
pianos](https://www.youtube.com/watch?v=ktxkEBT5CB0) where MIDI triggers
generate sequences of associated notes, chords and "ripples" in a
separate instrument or player piano.

Other generative music involves complex algorithms, probability triggers
and modulations to create ever-changing sounds, sequences, rhythms.
[Often these are programmed via modular synth
rigs](https://www.youtube.com/watch?v=uNz1XfVfJak) using LFOs,
sequencers, quantizers, harmonic generators, bernoulli gates, Turing
machines.

It's your choice what you do with these generative parts - either
shorter, reactive sequences or long infinitely varying sequences.
Through modulation and automation it's possible to create music where
the sounds evolve, appear, disappear, blend or create dissonance. In
this book we'll try to present some ideas that will help get you started
on this journey. I recommend that you try out the ideas in practice. Let
the sequences play. Sit with them a while and let what you hear guide
what to try next...If you like what you hear, save it. If you like parts
of what you hear, save those as little self-contained ideas for use in
other tracks. If you don't like what you hear, then try replacing one or
more parts and repeat the process of listening and refining. You can
take the generative parts together to form a completely generative piece
of music, or you can take only one element and build a track around
that. Or you can take a snippet of one idea and use that as a kernel for
new sound design, resampling it or reusing it in a completely structured
and arranged piece of music.

This is only the beginning.
