# Recipe - Changing chords

1.  Create three MIDI tracks, each with a virtual synth instrument. I particularly like the default sound from Ableton's Operator synth - which is a sine-wave. Something with a reasonably fast attack will work for this recipe.

2.  Make three MIDI clips in each track.

3.  Prepare stacked chords (8 notes or so) from A minor, D minor, G minor in each clip within the tracks, avoiding notes that are specific to each scale in the clip. Avoiding 3rds will make the chords tonally "ambiguous", and avoiding 7ths will help the sounds produced blend between tracks and clips. Use the Scales functionality in Ableton to present notes within the scale. The chords suggested are arbitrary, but the recipe will work best if you use scales or chord intervals that are "next door" to each other in the cycle of 5ths - <https://en.wikipedia.org/wiki/Circle_of_fifths>).

4.  Use random note probability (a new feature in Live 11) on all notes in the chord, set at about 50-60% probability so that each time the clip triggers, the note choice / chord is different. This will mean that sometimes the chord will have 4 notes, but it could vary between 2 and 7... (in fact it could vary between none and 8, but the the extremes are very unlikely).

5.  Make sure that the clip lengths vary between tracks (all notes within the clip have the same length). So clip1 in track 1 could have 4 beat (1 bar) length; clip 1 in track 2 could have 5 beat length; clip 1 in track 3 could have 6 beat length etc. The important thing is not the clip length, but the fact that they vary ***across*** tracks.

6.  ALSO, vary clip lengths between scenes ***within*** tracks. So a track that has 4 beats in clip 1, maybe has 5 beats in clip 2 and 6 beats in clip 3. Similarly, the exact length is unimportant. The important thing is that the clip lengths vary both within tracks and between tracks. AVOID having the same clip lengths in the same scenes.\
    \
    Following the advice above you should wind up with something like this in the first three clip slots of the three tracks:

    | Track 1                 | Track 2                 | Track 3                 |
    |-------------------------|-------------------------|-------------------------|
    | Clip 1 - Amin - 4 beats | Clip 1 - Amin - 5 beats | Clip 1 - Amin - 6 beats |
    | Clip 2 - Dmin - 5 beats | Clip 2 - Dmin - 6 beats | Clip 2 - Dmin - 4 beats |
    | Clip 3 - Gmin - 6 beats | Clip 3 - Gmin - 4 beats | Clip 3 - Gmin - 5 beats |

7.  Set up Follow Actions (see the following chapter [Process - Follow Actions]) to progress to Next clip at end of each clip with 50% probability, with the other action set to "Play again" with 50% probability. When you launch the scene, each clip will play to the end of the clip, but because individual note probability within each of the stacked chords is set to 50-60%, the chord will sound different each time it plays. Also, the randomness we're using for note probability also means that the same chord clip in each track is also likely to sound different. The 50-50% split of next action - "Play again" or "Next" - will mean that some tracks may progress to the next chord while some will play the same clip again.

8.  Choose sounds for each track that complement each other. Could be pads, arpeggios, textures etc. Arpeggios and sounds that evolve are particularly useful in this recipe. You can automate parameters within clips as well to introduce additional movement in the sound. An important point is that the sound shouldn't be too static.

9.  Here I'm suggesting using (relatively) short clip lengths in order to quickly demonstrate how the recipe works. The recipe will also work with longer clips lengths - for example substituting bars for beats above. Having longer clips means that the playing clip has longer for the sound to evolve or for automation to happen (see Step 8). It's a matter of preference, choice of sound, etc.

10. Press play. Sit back and relax.

------------------------------------------------------------------------

You can hear one instance of this track here: <https://soundcloud.com/mikeksmith/changing-chords/s-LNeHFk2AeCI>

```{r, echo=FALSE, results="asis"}
htmltools::includeHTML(path = "Recipe1-Changing_Chords.html")

```

(I say "one instance" because this is generative and uses probability. So the next time I render the track it could well sound different. Similar, but different.)
