# Process - Using Field Recordings

> Computer goes "Bleep bloop bleep bleep bloopity bloop. Whoosh. Bleep
> bleep... BRRRRR...."

If the sound sources for your generative music using synths and sound
generators that don't involve sounds from "real world" instruments and
you add in random and probabilistic processes then pretty quickly you
have moved away from anything that could be described as "natural"
sounding. How can this kind of music appeal to humans, who by their
nature are more used to organic sounds and textures they hear day to
day?

::: callout-tip
## Key idea

Field recordings of nature, or sounds that humans might hear day to day
add back in context that might help listeners feel more engaged with the
generative and more random aspects of the music. The sound of a stream,
birds, rain, wind, people talking in a street and cars passing, even the
hum or mechanical clicks of machinery can help the listener create a
mental picture to go with the more abstract or generative ideas.
  
:::

## Balancing the natural and the (unnatural) randomness

Field recordings of natural, human sounds provide that balance between
something familiar, predictable and natural with random bleeps and
bloops. In 
[Process - Balancing the unexpected and the predictable](009-Process-Balance_unexpected_and_predictable.qmd)
 we discussed
providing musical balance to the randomness. In this chapter we're
talking about using field recordings to provide that balance.

## Natural and urban sounds

Take a walk in a woodland area. It's never entirely silent. There's
likely the sound of wildlife, wind in the trees, perhaps the sound of
water. By describing it to you now, I'm sure you have a mental picture
(even though it's sound!) of what you might expect to hear. Similarly,
you can use urban sounds (street sounds), sounds from the house,
mechanical noises - basically anything that listeners might be familiar
with.

## Randomness does occur in "natural" sounds

The sound of a wind-chime is often thought of as soothing. The wind gently 
causing the chimes to sound, little waves of air that cause the chimes to gently
ripple, with the chimes tuned to pitches that work well 
together... Sounds a lot like some of the techniques we've been talking about,
right?

The sound of birds singing in the forest, with the odd chirp of a squirrel or 
the steady rasp of a frog. Nobody is telling them when to make sounds. It's all
pretty much random. So why (again!) is it that our brains think of these sounds 
as soothing? 

I think the trick here is that we have context for the randomness. When we hear
those sounds we know how they occur and where. But this underlines (at least for
me) how adding context or something relateable to our compositions can help the
listener engage better.

## Recording noises

You likely have a phone with you now, or perhaps nearby. In that case
you have a microphone to hand. So next time you're out for a walk, take
out the phone and record some noises. All you need to do is to be ready
to listen and decide how the sounds you're hearing are interesting, or
how they could be contextualised (or provide context). The fidelity of
these recordings doesn't have to be astounding, after all, they are
likely to be low in the mix. But minimising wind noise or handling
sounds if you can will help the later "clean up" and integration of
these sounds into the music. Use of EQ to remove low end or high end
noises might be necessary.

## Online sources for field recordings

Many producers create field recording sound packs, and some of these are
sold through places like Bandcamp. Searching for "Field Recordings"
should allow you to find these. Please do check licensing terms and conditions
before you reuse these in your own compositions though!

## Using the samples

You can use these as is, alternatively you might want to put the sample
into Ableton's Simpler and have a MIDI note trigger the sample but with
random modulation on the sample start point. This will vary the starting
point of the sample with each MIDI note and allow you to effectively
extend the length of the sample to an arbitrary extent.
