# Process - Maximalist ambient

Not all ambient music goes plinky, plonky, drowned in reverb and delay. Some is harsh, abrasive, challenging and fills the entire sonic spectrum with noise. The key feature is slowness and evolution, rather than quiet.

------------------------------------------------------------------------

## Key idea {.unnumbered}

Rather than focussing on delicate and minimalist, create huge vistas, drones. Saturate the sonic palette and create a sound that is impossible to ignore. Remember to keep the sounds, chords, harmonics evolving rather than static to give the listener some room to breathe, but do not be afraid to make the sound not just heard but felt in the core of the listener's being.

------------------------------------------------------------------------

## Make it loud

Many of the sounds and ideas that have been presented so far are delicate, curated carefully to present the listener with something that is unobtrusive yet engaging. Another approach entirely is to make sounds that do not give the listener the opportunity to ignore them, designed to be played as loudly as possible through a sound system that has the potential to inflict hearing damage and rearrange internal organs.

Artists like Sunn O))), Alessandro Cortini, Norah Lorway have produced albums and tracks that are designed to played as loudly as possible. A common feature of these tracks is a slowly evolving soundscape (very ambient) but also harmonics, overtones, noise, saturation, distortion that itself adds to the sonic palette making it impossible to ignore.

## Slow evolution but noisy

To harness this concept, it pays to have more slow movement, rather than busy parts. Stacking sounds, detuning oscillators and sound sources will provide a depth and modulation to the sounds that can then be picked up and effected. Using parallel saturation and distortion will further expand the sound and allow you to process different parts of the sonic frequency separately, bringing out overtones rather than squashing them.

Make chords evolve rather than appear so that the listener is carried forward. The listener's senses will be pummeled by the sound itself rather than by rhythmic elements or rapid chord changes.

Remember: more is more, in this case.

## Blender rather than mixer

The challenging part of this is to bring the sounds together so that they blend and provide a cohesive whole. With saturation and distortion in many places and potentially with different effects, getting these to come together and not pile up in the sonic spectrum is difficult. Carving space for each, applying generous EQ to harness certain frequencies will be essential to making the elements sit together. This is usually how we mix tracks, but in this case where each sound is full and then saturate or distorted it's important to manage the whole, as well as the individual parts.

## Some examples:

-   Alessandro Cortini - Volume Massimo. <https://cortini.bandcamp.com/album/volume-massimo>

-   Sunn O))) - Pyroclasts. <https://sunn.bandcamp.com/album/pyroclasts>

-   Norah Lorway - digitalOceans. <https://xylemrecords.bandcamp.com/album/digitaloceans>
