# Process - Your Unpredictable Bandmate {#023-Process-Your_Unpredictable_Bandmate}

```{r}
#| echo: FALSE
knitr::opts_chunk$set(echo = FALSE)
```



::: callout-tip
## Key idea

Using probability, randomness and modulation to create generative parts or ideas
can create parts that inspire new ideas or can accompany you, the producer, in
ways that are less likely to stray into tropes and well-trodden paths. You can
view these generative parts as almost like an unpredictable bandmate, who
occasionally throws in an unexpected chord change, or an interesting phrase or
drum fill that maybe you weren't expecting. Being able to react to those
unexpected moments can help inspire you in new directions, keeping you and the
listener engaged.

::: 

## Unpredictable in a good way

When I say "your unpredictable bandmate" I'm not meaning like a person who shows
up late, or forgets that gig is on... More like a bandmate who is inspiring and
occasionally plays an interesting phrase or takes the melody or harmony somewhere 
new. The beauty of playing with others is that you never know what they're going
to do, and being able to react to that, play along and improvise to that new 
idea is the essence of ensemble playing.

So setting up a little randomness and probability in your music can help break
out of parts that are predictable, linear and that always follow the same path.
The methods we've discussed in this book should give you some ideas of how to 
set up parts that introduce unpredictability, but in a way that is interesting
and inspiring rather than chaotic.

## Unpredictable in a predictable way.

Again, we don't want a virtual bandmate to suddenly change key, tempo or pulse so it's important to constrain the amount of probability and randomness to something that sounds good to you and uses scale quantisers, pre-written phrases (but where which specific one is going to play is somewhat random) and modulation that breathes movement and life into parts without being overwhelming. So, like writing a melody, picking chord changes that inspire and rhythmic parts that provide energy and drive, you The non-Lazy Producer should be listening carefully and diailing in your unpredictable parts to provide ***just the right amount*** of uncertainty.

## Unpredictable like improvisation

The art of improvisation is about reacting to what you hear others playing. This does ***NOT*** mean unprepared. In fact, the better the preparation, the better the improvisation. So you can set up your randomness and probability to generate phrases, fills, weird rhythms, change chords, throw in some interesting notes in melodies. But maybe the best way to work with that is to improvise alongside it. If you're able. 

## Unpredictable shouldn't mean unpleasant.

Don't forget that ***you*** are in control of your unpredictable bandmate. If you don't like what you're hearing, change it. Try again. Bin it. Sack them and find a replacement. Genuinely... Don't feel obliged to follow any rule of "I ***must*** use this idea...". It may not work for you in this context. But it might in the next.
